#!/bin/bash

rm *.o -f

g++ -c distributer.cpp
g++ -c distributable_job.cpp
g++ -c counter.cpp
g++ -c process_client_manager.cpp
g++ -c process_client.cpp
g++ -c waiting.cpp

g++ main.cpp distributer.o distributable_job.o counter.o process_client.o process_client_manager.o waiting.o -o counter 
