#!/bin/bash

rm *.o -f

g++ -g -c distributer.cpp
g++ -g -c distributable_job.cpp
g++ -g -c counter.cpp
g++ -g -c job_unit.cpp
g++ -g -c process_clients_manager.cpp
g++ -g -c process_client.cpp
g++ -g -c waiting.cpp

g++ -g main.cpp -lboost_thread distributer.o job_unit.o distributable_job.o counter.o process_client.o process_clients_manager.o waiting.o -o counter 
