#!/bin/bash

BOOST_INCLUDE_DIR="/usr/include/boost-1_38/"

GROMACS_INCLUDE_DIR="/usr/local/gromacs/include/gromacs/"

# LDFLAGS="-L/usr/local/gromacs/lib -lboost_thread-gcc43-mt -lgmx"
LDFLAGS+="-L/usr/local/gromacs/lib -lgmx -lboost_thread-gcc43-mt "
#LDFLAGS="boost_thread"

# WARNINGS="-Wall -Weffc++ "
WARNINGS="-Wall "

rm */*.o -f

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c distributer-layer/distributer.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c distributer-layer/distributable_job.cpp
g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c distributer-layer/job_unit.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/coord3d.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/rmsd.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/structure.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/gmx_structs_db.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/sequentialDB.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/structuresDB.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/structures_db.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c main-app-layer/representatives_job.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c clients-layer/threads_clients_manager.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c clients-layer/client.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/  $LDFLAGS -c clients-layer/clusterer_threads_client.cpp

g++  $1 $WARNINGS -I$BOOST_INCLUDE_DIR -I$GROMACS_INCLUDE_DIR -Idistributer-layer/ -Imain-app-layer/ -Imisc/ -Iclients-layer/ $LDFLAGS main-app-layer/clusterer_threads.cpp distributer.o job_unit.o distributable_job.o representatives_job.o clusterer_threads_client.o coord3d.o rmsd.o structuresDB.o gmx_structs_db.o structure.o sequentialDB.o client.o threads_clients_manager.o structures_db.o -o ./clusterer_threads

